version: "1.0"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: MOTOR_INSURANCE_WEBSITE
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
